version: "3.9"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/angelopellizzon90/backend-node-docker-lab1:lab-1
    container_name: node_app
    restart: always
    ports:
      - "3000:4000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:9.4
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"

volumes:
  mysql_data:
